require 'pry'
require 'greenjaguar'
require 'byebug'
require 'minitest'
require 'webmock/rspec'

require_relative '../lib/greenjaguar/strategies/default_wait_strategy'
require_relative '../lib/greenjaguar/strategies/fibonacci_strategy'
require_relative '../lib/greenjaguar/strategies/exponential_backoff_strategy'
require_relative '../lib/greenjaguar/strategies/default_wait_strategy'
require_relative '../lib/greenjaguar/retrier'